Add custom aggregation units API
line/line-bot-sdk-ruby pull request #247
Opened 2021-12-27 07:35 UTC by yskkin

closes #219

2022-01-14 14:15 UTC, zenizh requested changes
Thanks for the contribution! I've made a few comments to check out. cc: @kimoto

2022-01-14 14:15 UTC, zenizh commented on lib/line/bot/client.rb
> +      # @param start [String] Value of the continuation token found in the next property of the JSON object returned in the response.
[nice to have]
It is better to express the property name as a code.

```suggestion
      # @param start [String] Value of the continuation token found in the `next` property of the JSON object returned in the response.
```

2022-01-14 14:15 UTC, zenizh commented on lib/line/bot/client.rb
> +      def get_unit_names(limit: nil, start: nil)
[nice to have]
This method name is very generic and could be the same as any other endpoint. A method name based on the endpoint would be preferred.

```suggestion
      def get_aggregation_list(limit: nil, start: nil)
```

2022-01-14 14:15 UTC, zenizh commented on lib/line/bot/client.rb
> +        endpoint_path = "/bot/message/aggregation/list?" + + URI.encode_www_form(params)
[must fix]
Unnecessary `+` is present. This is not an error, but should be removed.

```suggestion
        endpoint_path = "/bot/message/aggregation/list?" + URI.encode_www_form(params)
```

2022-01-19 04:29 UTC, zenizh approved these changes
Thank you for fixing about my suggestion. LGTM!

2022-01-24 06:32 UTC, kimoto commented
Sorry, Too late response. I will confirming it.

2022-01-24 06:37 UTC, kimoto approved these changes

2022-01-27 02:36 UTC, merged